version: 2
jobs:
  build:
    working_directory: ~/backend
    branches:
      only:
        - master
    docker:
      - image: becelot/awscli-node
    steps:
      - checkout
      - restore_cache:
            keys:
                - v1-npm-deps-{{ checksum "package-lock.json" }}
                - v1-npm-deps-
      - run:
          name: Install dependencies
          command: |
            npm install
      - save_cache: # cache Python dependencies using checksum of Pipfile as the cache-key
            key: v1-npm-deps-{{ checksum "package-lock.json" }}
            paths:
                - "./node_modules"
      - run:
          name: Package
          command: |
            export NODE_OPTIONS=--max-old-space-size=4096
            npx sls package
  deploy:
    branches:
      only:
        - master
    machine:
      enabled: true
    working_directory: ~/backend
    steps:
      - checkout
      - run:
          name: Deploy to AWS
          command: |
            export NODE_OPTIONS=--max-old-space-size=4096
            npx sls deploy

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master